### ISSUE TITLE
'kubectl get' does not work as expected for some resources

### ISSUE THREAD

**Issue by ebisso** [kubernetes-retired/kui#9368]
**Describe the bug**
It seems that some less common resources as well as custom resources are not resolved to their correct kind/group when trying to list them via command `kubectl get`. Some cases which do not work for me are:
 `hpa`
`gateway` (istio)
`application` (argocd)

Command works correctly when resource is fully-qualified  (ex: `kubectl get horizontalpodautoscalers.autoscaling`)

**Steps to reproduce the behavior**

Ensure resource is known to server : `k explain hpa`
Try listing HPA using the command `k get hpa`

**Expected behavior**
Same behavior as when kubectl is run.

**Screenshots**
Fails when using a resource 'shortname' or without the API group:
![image](https://github.com/kubernetes-sigs/kui/assets/3681011/a2320e3b-f95a-42fe-9011-90607e53126a)❌
![image](https://github.com/kubernetes-sigs/kui/assets/3681011/c0114ec3-3a0e-46f2-bfc1-31a1bb11de07)❌

Workaround: Specifying kind and group works as expected:
![image](https://github.com/kubernetes-sigs/kui/assets/3681011/dc3711a4-3eef-4ec2-b0ae-81d28c9e2dcf) ✔️

**System**

- Kui version: 13.1.4
- Operating system: Windows 10 22H2
- kubectl client version: 1.27.2
- Kubernetes server version 1.26.3

**Comment by starpit** [comment]
thanks for the bug report! we have indeed noticed some regressions with certain kinds of resources (especially custom CRDs). we'll investigate.
